name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # Sadece main branch'e push yapıldığında çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: contact_systeem  # Elastic Beanstalk uygulama adı
        environment_name: Contactsysteem-env  # Elastic Beanstalk ortam adı
        region: eu-north-1a  # AWS bölgesini burada belirtin    
        version_label: v1-2
        deployment_package: target/contact-system-0.0.1-SNAPSHOT.jar
